### ISSUE TITLE
Implement the project as per the requirements described under uca2018/es6-project/

### ISSUE THREAD

**Issue by mittalvaibhav** [mittalvaibhav/uca2018#1]

**Comment by Chelsea31** [comment]
Solution : https://chelsea31.github.io/Student-Details-webProject/
Source : https://github.com/Chelsea31/Student-Details-webProject/tree/gh-pages

Roll no : 1510991628

**Comment by mittalvaibhav** [comment]
Chelsea31,
This is a new UI approach which I really like. Some comments;
  - Please provide the link to the code. 
  - Black & white colors causing high contrast. Can be improved
  - I don't see any data, so I am actually not sure how "Edit Student Detail" functionality will work. Can you add some sample data ?

**Comment by Chelsea31** [comment]
<ul>
<li>Here is the git repository, check the gh-pages branch:
https://github.com/Chelsea31/Student-Details-webProject
</li>
<li> Changed the colour scheme</li>
<li> You can add the data using the first option, since it uses arrays to store details, it is session specific.</li>

**Comment by mittalvaibhav** [comment]
Chelsea31, You deleted both Index.html and main.js, can u check it in ?

**Comment by Chelsea31** [comment]
You will have to check the <b>gh-pages branch</b>, since github uses that branch for repositories to host a website on github's server. I deleted the files from master since they were useless for the website.

https://github.com/Chelsea31/Student-Details-webProject/tree/gh-pages

**Comment by VishwashDhiman** [comment]
https://vishwashdhiman.github.io/StudentDetails/

This is my solution for code

**Comment by skb1129** [comment]
I made the solution for the problem.
Roll No. - 1510991666
[Link to the Live Page](http://suryakantbansal.me/web-development/)
[Link to the Source Code](https://github.com/skb1129/web-development/tree/master/docs)
All the mentioned functionality is working.
I used Bootstrap for the styling & responsiveness and SweetAlert2 for the alert boxes.

**Comment by mittalvaibhav** [comment]
skb1129 ,
UI looks idea, I see that you have used bootstrap styling entirely. Popups also looks good and very interactive.

Some comments:
Add validation for data entry fields (e.g., I can enter string in year fiels, it hsould only allow numerics)
Still using old for loop, Make use of latest ES6 (for of) loop
Add dynamic serial number when we add new data

Questions:
Do we have any limit of number of row that will be displayed, can you implement pagination in case 100s of students are present.
Also in case of small screen size, can you implement horizontal scrolling in the table ?

**Comment by skb1129** [comment]
I will add validation and dynamic serial number.
I used the (for of) loop in some places but not all of them.
No there is no limit on number of rows so I will add pagination.
For small screen size, do you mean scroll inside the table window without scrolling the page?

**Comment by mittalvaibhav** [comment]
Skb1129
Yes, scroll bar inside table only without page scroll

**Comment by skb1129** [comment]
Please recheck the same links in the previous comment.
I have added all the validations I can think of. Let me know if more of them are needed.
I replace all the old for loops with for...of loop.
Dynamic serial no. in the table is added.

I was working on pagination and table scrolling but it is messing up the bootstrap's design of the table.

Also I just thought that I could use the knockout javascript framework to fill in the data entries in the table. It would get a lot easier.

**Comment by akashatri** [comment]
Roll No. =1510991042
Live Page: https://akashatri.github.io/student_management_portal/
Source Code: https://github.com/akashatri/student_management_portal/tree/gh-pages

**Comment by gur1preet** [comment]
Roll No.: 1510991223
Live Page: https://gur1preet.github.io/StudentDetails/
Source Code: https://github.com/gur1preet/StudentDetails

**Comment by VishwashDhiman** [comment]
Roll No: 1510991736
Live Page For Problum:-https://vishwashdhiman.github.io/StudentDetails/
Source Code:-https://github.com/VishwashDhiman/StudentDetails/tree/gh-pages

**Comment by airishgupta** [comment]
Roll Number :- 1510991034
Live Page For Student Portal - https://airishgupta.github.io/Student-Portal/
Source Code :- https://github.com/AIRISHGUPTA/Student-Portal

**Comment by adityasanghi96** [comment]
Roll Number :- 1510991031
Live Page :- https://adityasanghi96.github.io/StudentPortal/
Source Code :- https://github.com/adityasanghi96/StudentPortal

**Comment by puneetamb240** [comment]
Live Page:-https://puneetamb240.github.io/student-portal/
Source Code:-https://github.com/puneetamb240/student-portal

**Comment by sahiljain2497** [comment]
Roll Number : 1510991559
Live Page : https://sahiljain2497.github.io/Student-Management-ES6/
Source Code : https://github.com/sahiljain2497/Student-Management-ES6

**Comment by apoorvbansal** [comment]
Roll number: 1510991105
Live Page:-https://apoorvbansal.github.io/Student-Details-Portal/
Source Code:-https://github.com/apoorvbansal/Student-Details-Portal

**Comment by Sahil624** [comment]
Roll Number :- 1510991556

[Live page](https://sahil624.github.io/student-managment-project/)

[Source Code](https://github.com/Sahil624/student-managment-project)

**Comment by goyalmunish85** [comment]
Roll No. :- 1510991389
Live Page :- https://goyalmunish85.github.io/studentManagementPortal/
Source Code :- https://github.com/goyalmunish85/studentManagementPortal

**Comment by ghost** [comment]
Live Page:-https://pallvigoel.github.io/studentproject/
Source-page:-https://github.com/pallvigoel/studentproject
Sir, let me know if any changes are needed.
Roll No:-1510991432

**Comment by anuragwadhwa22** [comment]
Roll Number :- 1510991103
Live Page:-https://anuragwadhwa22.github.io/student_portal1/
Source Code:-https://github.com/anuragwadhwa22/student_portal1

**Comment by anchit003** [comment]
Roll Number :- 1510991072
Live Page:- https://anchit003.github.io/Student-Portal/
Source code:-https://github.com/anchit003/Student-Portal

**Comment by nidhikapoor21** [comment]
Roll number: 1510991406
Live page:- https://nkapoor21.github.io/Student_Portal/
Source code:- https://github.com/Nkapoor21/Student_Portal.git

**Comment by neha382852** [comment]
Roll number: 1510991404
Live page:-  https://neha382852.github.io/Student-Portal/
Source code:- https://github.com/neha382852/Student-Portal.git

**Comment by namankharbanda** [comment]
Roll number; 1510991393
Live Page:-  https://namankharbanda.github.io/student_portal/
Source Code:- https://github.com/namankharbanda/student_portal.git

**Comment by ananyasethi56** [comment]
Source Code:- https://github.com/ananyasethi56/Student-Details.git
Live Page:-  https://ananyasethi56.github.io/Student-Details/
Rollno-1510991071

**Comment by Divyansh3007** [comment]
**Live page** : https://divyansh3007.github.io/Studentdetailsportal/
**Source code** : https://github.com/Divyansh3007/Studentdetailsportal
roll no. 1510991197

**Comment by MadaZZ** [comment]
1510991658
Source-Code:-https://github.com/MadaZZ/Web-Dev-Class/tree/master/project_1

**Comment by mittalvaibhav** [comment]
Please add you roll number along with the comment. Edit the your current comment only and add your roll number as below:
 
Roll Number: xxxxxx
Live page : https:xxxxx/Studentdetailsportal/
Source code : https://xxx/Studentdetailsportal

**Comment by AkankshaJain1607** [comment]
live page: https://akankshajain1607.github.io/student-detail-management-portal/
source code: https://github.com/AkankshaJain1607/student-detail-management-portal

**Comment by Upasana1997** [comment]
Roll Number: 1510991698
Live page: https://Upasana1997.github.io/studentdetailsportal/
source code: https://github.com/Upasana1997/studentdetailsportal

**Comment by ArshdeepSingh-developer** [comment]
Roll Number : 1510991119
source code: https://github.com/arshdeeparora/studentrecordproject
Live page: https://arshdeeparora.github.io/studentrecordproject/

**Comment by nikhil16-bhaskar** [comment]
roll no: 1510991408
source code: https://github.com/nikhil16-bhaskar/Web-Development-Recipes/tree/master/studentDetails-ES6

**Comment by AkankshaJain1607** [comment]
Roll Number: 1510991039
Live Page: https://akankshajain1607.github.io/student-details-management-portal/
Source Code: https://github.com/AkankshaJain1607/student-details-management-portal

**Comment by Mehak97** [comment]
Roll Number:1510991379
source code: https://github.com/Mehak97/Web-Development

**Comment by shireen99** [comment]
Roll Number: **1510991599**
Live page : https://shireen99.github.io/Studentdetailsportal/
Source code : https://github.com/shireen99/Studentdetailsportal

**Comment by puneetamb240** [comment]
Roll No: 1510991477
Live Page: https://puneetamb240.github.io/es6project/Index.html
source code: https://github.com/puneetamb240/es6project

**Comment by vmvilas9** [comment]
Roll No: 1510991725
Live page : https://vmvilas9.github.io/Student-Management/
Source Code: https://github.com/vmvilas9/Student-Management

**Comment by Shivang-Bhandari** [comment]
* Roll Number : `1510991614`
* [Hosted Repo](https://shivang-bhandari.github.io/ES6-UCA)
* [Source Code](https://github.com/Shivang-Bhandari/ES6-UCA)

**Comment by tarunwadhwa13** [comment]
Roll number : 15109991682 
Live Page :- https://tarunwadhwa13.github.io/Student-Details-Management/
Source Code :- https://github.com/tarunwadhwa13/Student-Details-Management

**Comment by shefali97** [comment]
Roll  Number: 1510991594
Live Page: https://shefali97.github.io/es6-project/.
Source Code: https://github.com/shefali97/es6-project

**Comment by shivamgupta0897** [comment]
Roll no- 1510991605
Live page- https://shivamgupta0897.github.io/Es6proj/
Source Code- https://github.com/shivamgupta0897/Es6proj

**Comment by harshitagupta1404** [comment]
Roll No-1510991244
Live Page-https://harshitagupta1404.github.io/Student-Detail-Portal/.
Source Code-https://github.com/harshitagupta1404/Student-Detail-Portal
Sir, the image is not being displayed. Although i have uploaded it on github

**Comment by IshaSaxena9** [comment]
Roll No: 1510991271
Live Page: https://ishasaxena9.github.io/Student_DetailsPortal/
Source Code: https://github.com/IshaSaxena9/Student_DetailsPortal

**Comment by karansingla-dev** [comment]
Roll Number : 1510991314
Source Code : https://github.com/singlakaran/student-details-management
Live Page : https://singlakaran.github.io/student-details-management/studentData.html

**Comment by psimran** [comment]
Roll Number :1510991444
Live Page:- https://psimran.github.io/student-portal/
Source Code:-https://github.com/psimran/student-portal

**Comment by ruchita2325** [comment]
Roll Number : 1510991546
Source Code : https://github.com/ruchita2325/ProjectWeb/
Live Page : https://ruchita2325.github.io/ProjectWeb/

**Comment by everythings13** [comment]
Roll No. : 1510991104
Live Page: https://everythings13.github.io/StudentDetailsPortal/
Source Code: https://github.com/everythings13/StudentDetailsPortal

**Comment by negiankit97** [comment]
Roll number:1510991081
Source code:https://github.com/negiankit97/login

**Comment by SaloniGupta21** [comment]
Roll Number : 1510991575
Live Page : https://salonigupta21.github.io/StudentDetails/
Source Code : https://github.com/SaloniGupta21/StudentDetails/tree/gh-pages

**Comment by SimranSethi1** [comment]
Roll num: 1510991645
source Code :https://github.com/SimranSethi1/es6proj1
Live Page:https://simransethi1.github.io/es6proj1/

**Comment by SakshiJain97** [comment]
Roll No: 1510991572
[Live Page](https://sakshijain97.github.io/StudentDetailsES6/)
[Source Code](https://github.com/SakshiJain97/StudentDetailsES6)

**Comment by himanshudhiman1997** [comment]
Roll No: 1510991254
Source Code :  https://github.com/himanshudhiman1997/Student-Management-Portal/tree/gh-pages
Live-https://himanshudhiman1997.github.io/Student-Management-Portal/

**Comment by VritangiKansal** [comment]
Roll No. 1510991738
Live Page: https://vritangikansal.github.io/StudentPortal/
Source Code: https://github.com/VritangiKansal/StudentPortal/tree/gh-pages

**Comment by mohit472** [comment]
Roll no:1510991382
Live page : https://mohit472.github.io/Student-Details/
Source code : https://github.com/mohit472/Student-Details
