### ISSUE TITLE
UCA1 - ES6 project

### ISSUE THREAD

**Issue by mittalvaibhav** [mittalvaibhav/uca2018#4]
Implement the project as per the requirements described under uca2018/es6-project and share the details as per below format:

Roll No. : <XXXXX>
Source : <git repo url>

**Comment by damanasija** [comment]
Roll No: 1510991168
Source: https://github.com/damanasija/es6-project

Issues: Babel transpiled JS code not working. Original ES6 code works fine on Chrome.

**Comment by arooshrana2** [comment]
Roll No: 1510991114
Name: Aroosh Rana
Source: https://arooshrana2.github.io/UCA/ES6/Project1/index.html            (User Interface)
             https://github.com/arooshrana2/UCA/tree/master/ES6/Project1     (Code)

**Comment by RyanSun-dev** [comment]
Roll No:1510991336
Source: https://github.com/KrishnaBhatia/uca

**Comment by AnanyaAggarwal23** [comment]
Name: Ananya
Roll No: 1510991070
Live Page : https://ananyaaggarwal23.github.io/StudentPortal/
SourceCode : https://github.com/AnanyaAggarwal23/StudentPortal

**Comment by gursimar020** [comment]
Roll No - 1510991224
Live Page - https://gursimar020.github.io/ES6-Project/index.html
Source Code - https://github.com/gursimar020/ES6-Project

**Comment by AvleenK** [comment]
Name: Avleen Kaur
Roll No: 1510991138
Live Page: https://avleenk.github.io/es6project1/
Source Code: https://github.com/AvleenK/es6project1

**Comment by AdityaDhawan1997** [comment]
Name : Aditya Dhawan
1510991030
Live page: https://adityadhawan1997.github.io/student-portal/
Source code: https://github.com/AdityaDhawan1997/student-portal

**Comment by mohit654** [comment]
Name: Mohit Chawla
1510991383
Repository Link : https://github.com/mohit654/Student-Portal
Live Page Link : https://mohit654.github.io/Student-Portal/

**Comment by madhur-taneja** [comment]
Roll No. : 1510991354
[Source code](https://github.com/madhur-taneja/Student-Details-Portal)
[Live Version](https://madhur-taneja.github.io/Student-Details-Portal/index.html)

**Comment by ashutosh-sharma** [comment]
Roll No. : 1510991132 
Live :  https://ashutosh-sharma.github.io/student-portal-es6/
Source: https://github.com/ashutosh-sharma/student-portal-es6

**Comment by 451Gagan** [comment]
Roll No : 1510991204
Live page: https://451gagan.github.io/ES6-Project/
Source Code: https://github.com/451Gagan/ES6-Project

**Comment by Garima-Nanda** [comment]
Roll No. : 1510991205
Source: https://github.com/Garima-Nanda/ES6_Project
Live Page: https://garima-nanda.github.io/ES6_Project/

**Comment by Ankul007** [comment]
Roll No. : 1510991086
Source: https://github.com/Ankul007/Web-Programming
Live Page: https://ankul007.github.io/Web-Programming/

**Comment by maniksharma98144** [comment]
Name: Manik Sharma
Roll No: 1510991360
Source: https://github.com/maniksharma98144/Student-Management-Portal
Live Page: https://maniksharma98144.github.io/Student-Management-Portal/index.html

**Comment by ayaanfaiz** [comment]
Name - Ayaan Faiz
1510991140
Source code - https://github.com/ayaanfaiz/Student-Portal
Live - https://ayaanfaiz.github.io/Student-Portal/

**Comment by AkankshaGrover** [comment]
Name: Akanksha Grover
Roll No: 1510991038
Source Code: https://github.com/AkankshaGrover/studentPortal
Live: https://akankshagrover.github.io/studentPortal/

**Comment by damanpreetkaur** [comment]
Name: Damanpreet Kaur
Roll No: 1510991169
Source Code: [https://github.com/damanpreetkaur/ES6](url)

**Comment by chetanyachopra22** [comment]
Chetanya Chopra
1510991158
[LIVE](https://chetanyachopra.github.io/Student-Data-Management-Protal/index.html)
[Source Code](https://github.com/chetanyachopra/Student-Data-Management-Protal)

**Comment by kshitijmahajan72** [comment]
Kshitij Mahajan
1510991340
Source Code: [https://github.com/kshitijmahajan72/StudentPortal](url)

**Comment by sagarchoudhary96** [comment]
Sagar Choudhary
1510991552
 Source Code: https://github.com/sagarchoudhary96/StudentManagement-ES6
Live: https://sagarchoudhary96.github.io/StudentManagement-ES6/public/index.html

**Comment by jaikathuria** [comment]
Jai Kathuria
1510991281
[Source Code](https://github.com/jaikathuria/student-management-es6-uca)
[Live](https://jaikathuria.github.io/student-management-es6-uca/)

**Comment by sgurjeet** [comment]
Roll No : 1510991219
https://github.com/sgurjeet99/Student-Portal-ES6

**Comment by Nainika-aggarwal** [comment]
Nainika Aggarwal
Roll No. - 1510991392
Source code: https://github.com/Nainika-aggarwal/student-data

**Comment by mayankm1996** [comment]
Mayank Marwaha 
Roll No - 1510991375
Source Code: https://github.com/mayankm1996/student_mangement

**Comment by damanpreetkaur** [comment]
Damanpreet Kaur
Roll No.: 1510991169
Source Code: https://github.com/damanpreetkaur/ES6

**Comment by Asmita6** [comment]
Asmita
Roll No: 1510991131
Live Page: https://asmita6.github.io/Student-Portal/
Souce code: https://github.com/Asmita6/Student-Portal

**Comment by manikchhabra1275** [comment]
Manik Chhabra
Roll No: 1510991358
Souce code: https://github.com/manikchhabra1275/Student-Management-Portal-
Live Page: https://manikchhabra1275.github.io/Student-Management-Portal-/

**Comment by goelanshul321** [comment]
Anshul Goel
Roll No: 1510991095
Source Code:https://github.com/goelanshul321/es6-project

**Comment by angadbachhal** [comment]
Angad Bachhal
Roll No. 1510991073
Source Code: https://github.com/angadbachhal/es6-project

**Comment by himgupta2197** [comment]
Himanshu Gupta 
Roll no. 1510991256
Source Code: https://github.com/himgupta2197/es6-project

**Comment by jainsaurav52** [comment]
Saurav Jain
Roll No: 1510991587
Source Code: https://github.com/jainsaurav52/Student-Management-Portal-
Live Page: http://htmlpreview.github.io/?https://github.com/jainsaurav52/Student-Management-Portal-/blob/master/index.html
